ALTER PROCEDURE DELETE_FK (
		@PTABLENAME NVARCHAR(1000),
		@PARENTCOLUMN NVARCHAR(1000),
		@TABLENAME NVARCHAR(1000),	
		@FIRSTCHILD NVARCHAR(1000),
		@VALUE NVARCHAR(1000)
)
AS
DECLARE @TBL TABLE (
		[LEVEL] INT,
		ID INT IDENTITY(1,1),
		PTAB NVARCHAR(1000),
	    PCOL NVARCHAR(1000),
		CTAB NVARCHAR(1000),
		CCOL NVARCHAR(1000),
		S_NAME NVARCHAR(1000)
);

INSERT INTO @TBL([LEVEL],PTAB,PCOL,CTAB,CCOL) VALUES (1,@PTABLENAME,@PARENTCOLUMN,@TABLENAME,@FIRSTCHILD)

DECLARE @CURRENTLEVEL INT = 1
DECLARE @cSQL NVARCHAR(1000)

WHILE 1=1
BEGIN
INSERT INTO @TBL([LEVEL],CTAB,CCOL,PTAB,PCOL,S_NAME)
SELECT	
		@CURRENTLEVEL + 1,
		CT.name AS CHILDTABLE,
		CC.name AS CHILDCOLUMN,
		PT.name AS PARENTTABLE,
		PC.name AS PARENTCOLUMN,
		SS.name AS S_NAME
FROM sys.foreign_key_columns KC
	INNER JOIN sys.tables  PT ON PT.[object_id] = KC.referenced_object_id
	INNER JOIN sys.columns PC ON PC.[object_id] = KC.referenced_object_id AND PC.column_id = KC.referenced_column_id
	INNER JOIN sys.tables  CT ON CT.[object_id] = KC.parent_object_id
	INNER JOIN sys.columns CC ON CC.[object_id] = KC.parent_object_id AND CC.column_id = KC.parent_column_id
	INNER JOIN sys.schemas SS ON SS.[schema_id] = CT.[schema_id] 
    INNER JOIN sys.objects SO ON KC.constraint_object_id = SO.[object_id]

WHERE PT.[name] IN(SELECT CTAB FROM @TBL WHERE [LEVEL] = @CURRENTLEVEL)
	  AND CT.name NOT IN(SELECT CTAB FROM @TBL) 

	IF NOT EXISTS(SELECT TOP(1) 1 FROM @TBL WHERE [LEVEL] = @CURRENTLEVEL) 
		  BREAK	

SET @CURRENTLEVEL = @CURRENTLEVEL + 1
SELECT *FROM @TBL
END

DECLARE	@DEGER INT,
		@CTAB2 NVARCHAR(1000),
	    @CCOL2 NVARCHAR(1000),
		@name NVARCHAR(1000)
DECLARE CRS2 CURSOR LOCAL FOR
	SELECT ID,CTAB,CCOL,S_NAME FROM @TBL ORDER BY ID DESC
OPEN CRS2
FETCH NEXT FROM CRS2 INTO @DEGER,@CTAB2,@CCOL2,@name
WHILE @@FETCH_STATUS =0
    BEGIN
		SET @cSQL = 'DISABLE TRIGGER ALL ON ' +@name+'.' + @CTAB2 + '; DELETE FROM '+@name+'.'+@CTAB2+ ' WHERE ' + @CCOL2+ ' = ' + @VALUE
		print @cSQL
		EXEC sp_ExecuteSQL @cSQL
FETCH NEXT FROM CRS2 INTO @DEGER,@CTAB2,@CCOL2,@name
    END
CLOSE CRS2
DEALLOCATE CRS2
GO 

exec DELETE_FK NULL,NULL,HOTEL,ID,7832
